### ISSUE TITLE
Cannot deploy using instructions - Vercel 404 Error

### ISSUE THREAD

**Issue by markojak** [mddanishyusuf/gumroad-coffee-template#4]
I followed the instructions pretty much exactly as they appeared in the README.md and have the following error after using Vercel to import and deploy the project
```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: gnxr8-1593720602280-c346cfa77cfc:bru1::j4sls-1593720602331-
```

Further comments:
- The Gumroad access token creation requires a redirect URL. Nothing is in the documentation about this so I just set my own website

**Comment by markojak** [comment]
To add a bit of a comment here it appears that the issue is related to this:
https://github.com/vercel/vercel/issues/3294

**Comment by mddanishyusuf** [comment]
Hey, @markojak This is not the code issue. Try to change `now.json` in your code.

Redirect page you have to set `http://supportme.vercel.app/thanks-coffee`

**Comment by mddanishyusuf** [comment]
I just deploy your repo on my vercel account and it's worked on one go. [https://support-nine.vercel.app/](https://support-nine.vercel.app/)
